source 'https://github.com/CocoaPods/Specs.git'

target 'NYTPhotoViewer' do
  pod "NYTPhotoViewer", :path => "../"
end

target 'Tests' do
  pod "NYTPhotoViewer", :path => "../"
  pod 'OCMock', '~> 3.2'
end

target 'NYTPhotoViewer-Swift' do
    pod "NYTPhotoViewer", :path => "../"
end

target 'NYTPhotoViewer-SwiftTests' do
    pod "NYTPhotoViewer", :path => "../"
    pod 'OCMock', '~> 3.2'
end
